### ISSUE TITLE
Registration failed as using GITHUB_REPO_OWNER instead of CONTEST_GITHUB_REPO_OWNER

### ISSUE THREAD

**Issue by Chomtana** [code-423n4/code423n4.com#2198]
As stated in the Readme.md: Use your GitHub username for GITHUB_REPO_OWNER

In my case, it is "Chomtana"

But it cause 404 errors as it looking for [code423n4.com](https://github.com/code-423n4/code423n4.com) owned by Chomtana which is not exists.

<img width="1853" alt="code4rena2" src="https://user-images.githubusercontent.com/4103490/173660533-8d2a9764-2915-4bc9-87da-133f8494da90.png">

It should use CONTEST_GITHUB_REPO_OWNER which is the official code-423n4/code423n4.com repository instead of user forked one.

Wrong: https://api.github.com/repos/Chomtana/code423n4.com/contents/_data%2Fhandles%2FChom.json
Correct: https://api.github.com/repos/code-423n4/code423n4.com/contents/_data%2Fhandles%2FChom.json

This pattern is repeated in many functions

**Comment by captainmangoC4** [comment]
The user data should all come from the user forked code4rena.com repo, but the contest github owner should just be used for submitting findings.

**Comment by captainmangoC4** [comment]
This is so that contributors can test registering/modifying user data in their forked repo without making pull requests to the main code4rena repo. The reason we also have `CONTEST_GITHUB_REPO_OWNER` which is set to code-423n4 is so that contributors can use the test contest repo that we set up and don't have to set up their own contest repos. The masons team should have write access to the test contest repo. But it's preferred for contributors to use `GITHUB_REPO_OWNER` in all cases involving user data (registering, fetching user info) so that we don't add unnecessary PRs to the main site repo.
