### ISSUE TITLE
Warden can steal identity of another user

### ISSUE THREAD

**Issue by csanuragjain** [code-423n4/code423n4.com#2201]
,Malicious Warden can use apply-for-certified-contributor function to steal identity of another warden.

Malicious warden can simply apply for certified contributor using victim warden handle and his own github username and email. Once verified, all private invite meant for victim warden will move to malicious warden

## Recommendation
One user should not be able to submit request for another user. Same fix required for other files like apply-for-judge.js

**Comment by sockdrawermoney** [comment]
Great catch. I would suggest that we also have folks authenticate to submit a help form as well (presuming that all help interactions are intended to come from wardens)

**Comment by captainmangoC4** [comment]
Since this would make 4/potentially 5 protected pages on the site (submit findings, register team, certified contributor application, judge application, and potentially help) we should make a `ProtectedPage` component that can show the generic "you must login to see this page" message if the user is not logged in.

**Comment by captainmangoC4** [comment]
I finished with requiring login for certified contributor and judge applications, but I'll hold off on requiring it for the help form until we know for sure there is no use-case where we'd want to allow non-registered users to request help.
