### ISSUE TITLE
[FEATURE]: Allow alternative login method to make submissions

### ISSUE THREAD

**Issue by sockdrawermoney** [code-423n4/code423n4.com#2763]
## Problem / opportunity:
- Wardens may not have access to hardware wallet or may have other constraints which make it inconvenient to log in using their wallet in order to make submissions.
- Right now we have a gapstop on form submissions, but unauthenticated submissions are not ideal as they require more diligence in order to prevent social engineering.

## Desired outcome
- Submission form allows an alternative sign-in method

## Solution
- Users can link a GitHub account and use that to log in.
- Could also add a magic link sign-in option.
- Users should receive a notification at their provided email address confirming that this was added to their account

**Comment by tealtigrrr** [comment]
@sockdrawermoney Doing an appetite check on this one: The team thinks this will take 1-1.5 weeks and would be worked on ~Aug 8 - 12. Does that sound good to you?

**Comment by tealtigrrr** [comment]
@sockdrawermoney after some discussion with @captainmangoC4 & @joshuashort I am proposing that we change the deliverable on this:

*Updated Deliverables:*
1. Table the idea of using Github (or other social sign on) for now
2. Pivot to using a simple username + password authentication as our alternative to MM & WC 
3. Retire the old, unathenticated submission form 
4. Add the username + password option to the "connect" dropdown in the nav and use a modal for the sign-in UI

*Why:*
On further investigation, it turns out that adding social sign-in (like GitHub) would be a pretty significant lift (we'd have to build a lot of stuff from scratch as it's not supported with our current Moralis set up), and (my assumption is) a larger one than we have appetite for, based on our current priorities.

Username + password, while not the jazziest option, will be quick to implement with Moralis and should still solve the issue of wallet-based log in issues.
__

Sound like a plan?
